# Generated by Django 5.1.4 on 2025-08-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('description', models.TextField()),
                ('skills', models.TextField(blank=True, help_text='Comma-separated (e.g. Manual, Automation, Selenium)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
